import { Geist, Geist_Mono } from "next/font/google";
import "@/styles/custom.scss";
import 'bootstrap-icons/font/bootstrap-icons.css'

import { SidebarProvider } from "@/context/SidebarContext";
import Navbar from "@/components/Navbar"
import Sidebar from "@/components/Sidebar"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={`${geistSans.variable} ${geistMono.variable}`}>
      <body className="bg-light">
        <SidebarProvider> 
        <Navbar />
        <Sidebar />
        {children}
        </SidebarProvider>
      </body>
    </html>
  );
}
